///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModalProfile {
/*
{
  "username": "string",
  "bio": "string",
  "image": "string",
  "following": true
} 
*/

  String? username;
  String? bio;
  String? image;
  bool? following;
  Map<String, dynamic> __origJson = {};

  UserModalProfile({
    this.username,
    this.bio,
    this.image,
    this.following,
  });
  UserModalProfile.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    username = json['username']?.toString();
    bio = json['bio']?.toString();
    image = json['image']?.toString();
    following = json['following'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['username'] = username;
    data['bio'] = bio;
    data['image'] = image;
    data['following'] = following;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class UserModal {
/*
{
  "profile": {
    "username": "string",
    "bio": "string",
    "image": "string",
    "following": true
  }
} 
*/

  UserModalProfile? profile;
  Map<String, dynamic> __origJson = {};

  UserModal({
    this.profile,
  });
  UserModal.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    profile = (json['profile'] != null)
        ? UserModalProfile.fromJson(json['profile'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (profile != null) {
      data['profile'] = profile!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
