///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginSuccessUser {
/*
{
  "email": "girish54321@gmail.com",
  "username": "Girish@54321",
  "bio": "null",
  "image": "https://api.realworld.io/images/smiley-cyrus.jpeg",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNzkwfSwiaWF0IjoxNzA1MjM0NzIxLCJleHAiOjE3MTA0MTg3MjF9.ks9tJrjdUg_3qcoUlMwXXh3R2lcTR-hal0OD3b8d5KY"
} 
*/

  String? email;
  String? username;
  String? bio;
  String? image;
  String? token;
  Map<String, dynamic> __origJson = {};

  LoginSuccessUser({
    this.email,
    this.username,
    this.bio,
    this.image,
    this.token,
  });
  LoginSuccessUser.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    email = json['email']?.toString();
    username = json['username']?.toString();
    bio = json['bio']?.toString();
    image = json['image']?.toString();
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['username'] = username;
    data['bio'] = bio;
    data['image'] = image;
    data['token'] = token;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class LoginSuccess {
/*
{
  "user": {
    "email": "girish54321@gmail.com",
    "username": "Girish@54321",
    "bio": "null",
    "image": "https://api.realworld.io/images/smiley-cyrus.jpeg",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNzkwfSwiaWF0IjoxNzA1MjM0NzIxLCJleHAiOjE3MTA0MTg3MjF9.ks9tJrjdUg_3qcoUlMwXXh3R2lcTR-hal0OD3b8d5KY"
  }
} 
*/

  LoginSuccessUser? user;
  Map<String, dynamic> __origJson = {};

  LoginSuccess({
    this.user,
  });
  LoginSuccess.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    user =
        (json['user'] != null) ? LoginSuccessUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
