///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginSuccess {
/*
{
  "token": "QpwL5tke4Pnpja7X4"
} 
*/

  String? token;

  LoginSuccess({
    this.token,
  });
  LoginSuccess.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    return data;
  }
}
